### ISSUE TITLE
Helm chart only works if deployed in default namespace

### ISSUE THREAD

**Issue by cablespaghetti** [jthomperoo/custom-pod-autoscaler-operator#64]
Just trying to deploy this in its own namespace on my cluster. The ClusterRoleBinding is hardcoded to look for the service account in the "default" namespace, where this should be templated out to look in {{ .Release.Namespace }}.

**Comment by jthomperoo** [comment]
Great, thanks for finding that! 
Put in that fix now, ran some tests on it and seems to resolve that issue when deploying cluster-wide into a specific namespace for helm.

One small caveat is that this only works for helm, due to this reference between the ClusterRoleBinding and the ServiceAccount being essentially dynamic. There's no way around this I can see for kubectl installs, so I've added a disclaimer for the kubectl cluster-scoped installation method.

This isn't a breaking change, so I'll cut a new release `v1.0.1` that will include this fix.

Thanks!
