### ISSUE TITLE
multiple service account token being created

### ISSUE THREAD

**Issue by dumplinginsoda** [jthomperoo/custom-pod-autoscaler-operator#67]
deployed operator through https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases/download/v1.0.0/cluster.yaml

Expected: 1 secret - 1 service account - 1 cpa 

Actual: multiple secrets - 1 service account(only 1 secret mountable) - 1 cpa

steps to reproduce:
1. create any cpa resource
2. kill the cpa pod (in our case, the pod was scheduled to other node)

when a cpa is being. re-span/killed, I was expecting either of them:
1. service account and service account token being garbage collected
2.  reconciling service account using the previously created service account token

Looks like neither of them happened, thus resulting in multiple unused service account token being created?

**Comment by jthomperoo** [comment]
Thanks for raising this. I've recreated this bug on `v1.0.1` of the Custom Pod Autoscaler Operator; I'm currently not sure why this is happening but going to investigate further and try to diagnose and fix it.

**Comment by dumplinginsoda** [comment]
thanks, I think it may related to this issue https://github.com/kubernetes/kubernetes/issues/84642.

reconciling the service account with same secret should resolve

**Comment by jthomperoo** [comment]
Thanks, that link was really good, discussion on that pointed me in the right direction.

The problem was that every time the CPA was reconciled by the operator (e.g. pod deletion) it updated the CPA service account, forgetting any reference to the old service account secret. K8s doesn't garbage collect these secrets until the service account is deleted, essentially meaning these would hang around forever. The solution in merge #68 is to copy any existing secrets over to the updated service account on every reconcile, ensuring that it reuses the same secret.

I'm just going to do some manual testing on this merge, if it all looks OK I'll merge it in, thanks for finding this!

**Comment by jthomperoo** [comment]
This fix is now available in release [`v1.0.2`](https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases/tag/v1.0.2). Thanks for raising this and helping debug it!
