### ISSUE TITLE
reconcile would delete existing pod during Update event

### ISSUE THREAD

**Issue by igorshevach** [jthomperoo/custom-pod-autoscaler-operator#86]
**Describe the bug**
On my local environment (docker-desktop) a phpa pod is being deleted every 10 minutes or so.

**To Reproduce**
1. Deploy operator and phpa
2. Run one of the examples coming with https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler
3. Watch for an UpdateEvent event sent to operator. This may take as long as 10+ min.
4.  Once event is consumed by operator compare between old and new states attached to an event object. Even if old and new states appear identical the pod will be scheduled for deletion inside Reconcile method.
    

**Expected behavior**
There should be evaluation of pod state differences before arriving at decision to delete the pod.

**Kubernetes Details (`kubectl version`):**
**kubectl version:** 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
**docker-desktop version:**
 4.5.0 (74594)
**docker version:**
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Custom Pod Autoscaler Operator Details:**
operator version: v1.2.0

**Additional context**
Probably being caused by https://github.com/jthomperoo/custom-pod-autoscaler-operator/issues/53

**Comment by jthomperoo** [comment]
I haven't actually been able to recreate this one - and it shouldn't really happen in the first place, the predicate that is applied to secondary resources (Pods, ServiceAccounts, etc.) purposefully skips Update events to prevent this:

```go
var SecondaryPred = predicate.Funcs{
	UpdateFunc: func(e event.UpdateEvent) bool {
		return false
	},
...
```

I installed [kubectl edit status](https://github.com/ulucinar/kubectl-edit-status)  to try manually modifying Pod status to recreate this, but as I expected the update event was filtered out by the predicate. I also tried then switching this to allow for update events in the predicate, and it was spammed with hundreds of events since it was constantly changing the status, so I don't think this is the underlying issue here, and unfortunately I can't seem to recreate this.

Closing unless there's further discussion/still affected by this.
